# f=open("k.txt","a")
# f.write("1234444")
# f.close()
#write a program to append the contents from one file into another text file
# f = open("file1.txt", "a+")
# # f2 = open("file2.txt", "r")
# f.write("python")
# s = f.read()
# print(s)
# # f.close()
# # f2.close()
# print(f.tell())
# f.seek(0)
#
# print(s)
# f = open("file1.txt", "a+")
# print("First Position ",f.tell())
# f.write('Python')
# print("Second Postion",f.tell())
# s=f.read()
# print("third Positon",f.tell())
# s=f.read()
# print(s)
# f.close()
